version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    environment:
      # для SQLAlchemy+psycopg3
      DATABASE_URL: postgresql+psycopg://task:task@db:5432/taskdb
      DEBUG: "false"
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app

volumes:
  dbdata:
